import os
import requests

def get_android_downloads_folder():
    possible_paths = [
        "/storage/emulated/0/Download",
        "/sdcard/Download",
        "/storage/self/primary/Download",
    ]
    for path in possible_paths:
        if os.path.exists(path):
            return path
    return os.getcwd()


def fetch_top_pages(max_pages=5, per_page=250):
    all_coins = []
    print(f"Fetching first {max_pages} pages from CoinGecko...")
    for page in range(1, max_pages + 1):
        url = "https://api.coingecko.com/api/v3/coins/markets"
        params = {
            "vs_currency": "usd",
            "order": "market_cap_desc",
            "per_page": per_page,
            "page": page,
            "price_change_percentage": "24h"
        }
        try:
            response = requests.get(url, params=params)
            if response.status_code == 429:
                print(f"Rate limited at page {page}, stopping fetch.")
                break
            response.raise_for_status()
        except Exception as e:
            print(f"Error fetching page {page}: {e}")
            break

        data = response.json()
        if not data:
            break

        all_coins.extend(data)
        print(f"Fetched page {page} ({len(data)} coins)")

    print(f"Total coins fetched: {len(all_coins)}")
    return all_coins

## Adjust Bubble Limit and Change Html File Name
def get_top_gainers_and_losers_html(limit=20, filename="24hr_Top_Gainers_Losers.html"):
    download_folder = get_android_downloads_folder()
    file_path = os.path.join(download_folder, filename)

    all_coins = fetch_top_pages(max_pages=5)

    coins_with_change = [c for c in all_coins if c.get("price_change_percentage_24h") is not None]

    # Top gainers and losers
    top_gainers = sorted(coins_with_change, key=lambda x: x["price_change_percentage_24h"], reverse=True)[:limit]
    top_losers = sorted(coins_with_change, key=lambda x: x["price_change_percentage_24h"])[:limit]

    # HTML structure
    html = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>24H Top Movers</title>
    <style>
        body { background: #f0f2f5; font-family: Arial, sans-serif; }
        h1, h2 { text-align: center; margin-top: 20px; }
        h1 { font-size: 32px; }
        h2 { font-size: 26px; margin-top: 40px; }
        .container { display: flex; flex-wrap: wrap; justify-content: center; margin-top: 20px; padding: 20px; border-radius: 12px; }
        .bubble {
            border-radius: 50%;
            width: 150px; height: 150px;
            margin: 15px;
            display: flex; flex-direction: column;
            align-items: center; justify-content: center;
            box-shadow: 0 4px 12px rgba(0,0,0,0.15);
            transition: 0.3s;
            background: white;
        }
        .bubble:hover { transform: scale(1.08); }
        img { width: 50px; height: 50px; border-radius: 50%; }
        .symbol { font-size: 18px; font-weight: bold; margin-top: 8px; word-wrap: break-word; text-align: center; }
        .percent { margin-top: 4px; font-size: 16px; font-weight: bold; text-align: center; }
        footer { text-align: center; margin-top: 20px; padding: 10px; color: #555; font-size: 14px; }
        .gainers-section { background: #f0f2f5; }
        .losers-section { background: #ffe6e6; } /* bearish light red/pink */
        .gainer-percent { color: green; }
        .loser-percent { color: red; }
    </style>
</head>
<body>
"""

    # Top Gainers Section
    html += """
    <h2>🔥 Top 20 Gainers (Last 24H)</h2>
    <div class="container gainers-section">
"""
    for coin in top_gainers:
        symbol = coin.get("symbol", "").upper()
        img = coin.get("image", "")
        percent = f"{coin.get('price_change_percentage_24h', 0):.2f}%"
        html += f"""        <div class="bubble">
            <img src="{img}" alt="{symbol}">
            <div class="symbol">{symbol}</div>
            <div class="percent gainer-percent">{percent}</div>
        </div>
"""
    html += """    </div>
    <footer>CTDGL v1.0 | Top Gainers | Generated by @TraderAbba</footer>
"""

    # Top Losers Section
    html += """
    <h2>💀 Top 20 Losers (Last 24H) </h2>
    <div class="container losers-section">
"""
    for coin in top_losers:
        symbol = coin.get("symbol", "").upper()
        img = coin.get("image", "")
        percent = f"{coin.get('price_change_percentage_24h', 0):.2f}%"
        html += f"""        <div class="bubble">
            <img src="{img}" alt="{symbol}">
            <div class="symbol">{symbol}</div>
            <div class="percent loser-percent">{percent}</div>
        </div>
"""
    html += """    </div>
    <footer>CTDGL v1.0  | Top Losers | Generated by @TraderAbba</footer>
</body>
</html>
"""

    with open(file_path, "w", encoding="utf-8") as f:
        f.write(html)

    print(f"HTML saved to: {file_path}")


if __name__ == "__main__":
    get_top_gainers_and_losers_html()